### ISSUE TITLE
Keyboard on screen

### ISSUE THREAD

**Issue by facferreira** [HACKERCHANNEL/PSL1GHT#85] opened 2011-02-12 16:40 UTC
I know it supports it fully, but I tried to adapt cellframework OSKUtil.cpp code to PSL1GHT, it compiles very well but doesn't work at all, may you provide a sample?

**Comment by Parlane** [comment] 2011-02-13 22:49
Closing comment due to being a duplicate of #83

**Comment by facferreira** [comment] 2011-02-13 23:12
Ok, I just hope that appear one answer for that issue. Thanks.

**Closed as completed** 2011-02-14 06:49 UTC
